### ISSUE TITLE
Circular require warning when loading under Rails 5

### ISSUE THREAD

**Issue by ijdickinson** [haml/haml#883] opened 2016-09-07 22:09 UTC
I have a Rails engine project that has been running fine under 4.2.3. Attempting to upgrade to Rails 5.0.0.1 today, I get a warning when I run my tests (see long stacktrace below).  What I'm not sure about is whether this was always occurring, and Rails 5 is now more picky about reporting the circularity, or whether it's a change introduced by Rails 5.

My tests still complete, but the warning makes for noisy log files.

Stack trace:

```
/home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293: warning: loading in progress, circular require considered harmful - /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/template.rb
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:4:in  `<main>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:4:in  `select'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:9:in  `block in <main>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:9:in  `each'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:10:in  `block (2 levels) in <main>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:10:in  `require'
from /home/ian/workspace/epimorphics/qonsole-rails/test/controllers/qonsole_rails/qonsole_controller_test.rb:1:in  `<top (required)>'
from /home/ian/workspace/epimorphics/qonsole-rails/test/controllers/qonsole_rails/qonsole_controller_test.rb:1:in  `require'
from /home/ian/workspace/epimorphics/qonsole-rails/test/test_helper.rb:23:in  `<top (required)>'
from /home/ian/workspace/epimorphics/qonsole-rails/test/test_helper.rb:23:in  `require'
from /home/ian/workspace/epimorphics/qonsole-rails/test/dummy/config/environment.rb:5:in  `<top (required)>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in  `method_missing'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in  `public_send'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in  `initialize!'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in  `run_initializers'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:205:in  `tsort_each'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:226:in  `tsort_each'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in  `each_strongly_connected_component'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in  `call'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in  `each'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:349:in  `block in each_strongly_connected_component'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:431:in  `each_strongly_connected_component_from'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:350:in  `block (2 levels) in each_strongly_connected_component'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:228:in  `block in tsort_each'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in  `block in run_initializers'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in  `run'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in  `instance_exec'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/railtie.rb:13:in  `block in <class:Railtie>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in  `load_dependency'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `block in require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/template.rb:3:in  `<top (required)>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in  `load_dependency'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `block in require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:1:in  `<top (required)>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:2:in  `<module:ActionView>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in  `load_dependency'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `block in require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionview-5.0.0.1/lib/action_view/base.rb:10:in  `<top (required)>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionview-5.0.0.1/lib/action_view/base.rb:139:in  `<module:ActionView>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionview-5.0.0.1/lib/action_view/base.rb:215:in  `<class:Base>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:44:in  `run_load_hooks'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:44:in  `each'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:45:in  `block in run_load_hooks'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in  `execute_hook'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in  `instance_eval'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/railtie.rb:5:in  `block (2 levels) in <top (required)>'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in  `load_dependency'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `block in require'
from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
```

After some investigation, the issue seems to be this hook that's installed in `railtie.rb`:

```
if defined?(ActiveSupport)
  require 'haml/template/options'
  ActiveSupport.on_load(:before_initialize) do
    ActiveSupport.on_load(:action_view) do
      require "haml/template"
    end
  end
end
```

Commenting out the `require` in the on-load hook makes the circular warning go away, which makes sense because line 13 in the same file is also already loading `haml/template`.

I don't have a minimal reproducible test case yet, but I'll work on creating one.

**Comment by lukaso** [comment] 2017-03-06 10:54
I think the fix is incorrect in that I'm seeing a different problem caused by the next require in the file where it requires the `haml/template` again. The problem I'm facing is that I can't load helpers when running view tests with haml. Here is the issue: https://github.com/rspec/rspec-rails/issues/1525 and here: https://github.com/rails/rails-controller-testing/issues/29

The fix for me was adding `unless defined?(ActiveSupport):
```ruby
      require "haml/template" unless defined?(ActiveSupport)
```

To `railtie.rb`:

```ruby
if defined?(ActiveSupport)
  require 'haml/template/options'
  ActiveSupport.on_load(:before_initialize) do
    ActiveSupport.on_load(:action_view) do
      require "haml/template"
    end
  end
end

module Haml
  class Railtie < ::Rails::Railtie
    initializer :haml do |app|
      require "haml/template" unless defined?(ActiveSupport)
      if defined?(::Sass::Rails::SassTemplate) && app.config.assets.enabled
        require "haml/sass_rails_filter"
      end
    end
  end
end

require "haml/helpers/safe_erubis_template"
Haml::Filters::Erb.template_class = Haml::SafeErubisTemplate
```

The problem is still there in haml 5.0.0.beta2 (not tested, just eyeballing the code).

The root cause is that `actionpack` and therefore `action_controller` gets loaded before the app has properly loaded it's helpers. This is caused by requiring `haml/template` too early.

By the by, this was incredibly hard to find for me because I assumed (wrongly) that `haml` had no dependency on `Rails` because of the existence of `haml-rails`.

Additionally, but I don't know for sure, I suspect that `ActiveSupport` will always be defined in a modern rails app, and since `haml` doesn't work without `rails` this doesn't need to be checked. But haven't done enough research to be sure. 

Here's the error message in my failing demo app:

```
  1) widgets/index SubdirHelperTest::Subdir calls the helper in _partial.html.erb
     Failure/Error: %p= some_different_helper("index.html.erb")

     ActionView::Template::Error:
       undefined method `some_different_helper' for #<#<Class:0x007fe0bd3f9ad0>:0x007fe0bd3e2f60>
     # ./app/views/widgets/index.html.haml:4:in `_app_views_widgets_index_html_haml___3934072388526033698_70301611691460'
     # ./spec/views/widgets/index.html.haml_spec.rb:51:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `some_different_helper' for #<#<Class:0x007fe0bd3f9ad0>:0x007fe0bd3e2f60>
     #   ./app/views/widgets/index.html.haml:4:in `_app_views_widgets_index_html_haml___3934072388526033698_70301611691460'

Finished in 0.07525 seconds (files took 22.28 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/views/widgets/index.html.haml_spec.rb:50 # widgets/index SubdirHelperTest::Subdir calls the helper in _partial.html.erb
```

**Comment by lukaso** [comment] 2017-03-06 11:12
Here is my sample project.

The steps to reproduce the problem.

1) clone, bundle, etc this repo:
```
git clone https://github.com/simplybusiness/rails5_helper_bug.git
cd rails5_helper_bug
bundle
```

2) 
```
git checkout erb
rails s
```
3) Navigate to `localhost:3000/widgets`
Everything works
4) Execute `bundle exec rspec spec/views/widgets/index.html.erb_spec.rb:50`
Everything works
5) 
```
git checkout master
rails s
```
6) Navigate to `localhost:3000/widgets`
Everything works
7) Execute: `bundle exec rspec spec/views/widgets/index.html.haml_spec.rb:50`
This will error as above.

If you apply my fix above or literally just comment out the second `require "haml/template"` everything works.

**Comment by k0kubun** [comment] 2017-03-28 15:38
https://github.com/haml/haml/pull/908 is merged to stable and ported to master.

**Closed by k0kubun** 2017-03-28 15:38 UTC
