### ISSUE TITLE
Exception on line 219: Old attributes must start with "{" and end with "}"

### ISSUE THREAD

**Issue by tablecell** [haml/haml#1073] opened 2021-09-05 10:16 UTC
test.haml
```C
%input{:name =>"mail" } Your friend's email
```
ruby -v
ruby 2.4.10p364
gem version 
haml-5.2.2 

$haml  test.haml
Exception on line 219: Old attributes must start with "{" and end with "}"
  Use --trace for backtrace.
$haml --trace test.haml

/ruby24-x64/lib/ruby/gems/2.4.0/gems/haml-5.2.2/lib/haml/parser.rb:219:in `old=': Old attributes must start with "{" and end with "}" (ArgumentError)

**Comment by ryanj-openquire** [comment] 2021-09-28 21:37
We are also hitting this exact same issue, Ruby 2.4.10 and haml 5.2.2. After binary chopping the source haml we discovered the issue is in plain user visible text containing a single quote, exactly as you have above in the text "Your friend's email".
IMO this is a really big regression as HAML that has been working since Rails 3.2 and 4.2 now fails. Without a code fix we're left to finding all cases of these and resolving them manually.

**Comment by tablecell** [comment] 2021-09-29 00:36
@ryanj-openquire

```slim
input type="text"  Your friend's email
```
   slimrb  test.slim
slim works fine

**Comment by ryanj-openquire** [comment] 2021-09-29 19:46
@tablecell 
add a data attribute, or some other attribute using standard HAML {} syntax

**Closed** 2022-08-18 20:17 UTC
