### ISSUE TITLE
Excess spaces while rendering multiline string

### ISSUE THREAD

**Issue by atomAltera** [haml/haml#869] opened 2016-03-01 07:15 UTC
Hello, today I end up with strange issue in Rails 5:

Here is how a simple _text.html.erb_ file looks like:
`<textarea><%= "a\nb\nc" %></textarea>`
And here is what it produce:
[![enter image description here](http://i.stack.imgur.com/qzTx4.png)](http://i.stack.imgur.com/qzTx4.png) [![enter image description here](http://i.stack.imgur.com/Z09F4.png)](http://i.stack.imgur.com/Z09F4.png)

I'm talking about these leading spaces before second and third strings.

In my code I have a form with textarea: 

```
.form
  =form_for article do |f|
    .form-group
      =field_label f, :text, true
      =f.text_area :text, class: %w(form-control), rows: 20, placeholder: t('placeholder.article_text')
```

And the same issue happens there on Edit action

I found out that the reason is haml-rails gem in Gemfile. Without it `<textarea><%= "a\nb\nc" %></textarea>` forks fine, but with it, it adds extra spaces.

**Comment by remomueller** [comment] 2016-03-11 14:35
I've run into the same issue when trying out the Rails 5 beta3. I've made a project that is a simple Rails 5 app that demonstrates the issue with haml 4.0.7 here:

https://github.com/remomueller/TextAreaSpacing

Note that the project does not have haml-rails in it. Hope that helps debugging, as I'd love to keep using Haml in Rails 5!

Here are some notes to launch the project:

# To Recreate

Clone code:

```
git clone https://github.com/remomueller/TextAreaSpacing.git
cd TextAreaSpacing
```

Launch Server
```
rails s
```

Open http://localhost:3000/items/new

Create item with

```
Name:
Name

Description:
My Description
Will have spaces in front of this line
```

Click "Create item"

![screen shot 2016-03-11 at 9 30 02 am](https://cloud.githubusercontent.com/assets/316479/13704950/7dbd2172-e76c-11e5-985c-ad9f605c3b09.png)


Click 'Edit'

Extra spacing will be in front of 'Will have spacecs'

![screen shot 2016-03-11 at 9 30 21 am](https://cloud.githubusercontent.com/assets/316479/13704955/852620d0-e76c-11e5-825b-2c9011c0ef77.png)

**Comment by remomueller** [comment] 2016-03-11 14:37
Just an FYI, this extra spacing can be fixed by doing the following on the form:

```
= f.text_area :description, value: item.description.to_s.gsub("\r\n", "\r")
```

**Comment by olivierlacan** [comment] 2016-09-17 02:38
@norman @amatsuda Any idea why this regression is occurring with Rails 5? Could be a coincidence with Ruby 2.3 maybe?

**Comment by olivierlacan** [comment] 2016-09-18 00:41
Just to isolate the issue I tried to run Rails 5 with Ruby 2.2 instead of 2.3 and the issue still occurs so something must have changed in Rails 5 to cause this.

**Comment by k0kubun** [comment] 2017-03-28 15:58
This may be resolved by Haml 5 because it doesn't have `ugly: false` mode. Please try Haml 5.0.0.beta.2 and reopen this if the problem still exists on Haml 5.

**Closed by k0kubun** 2017-03-28 15:58 UTC

**Comment by olivierlacan** [comment] 2017-04-08 00:11
@k0kubun I've tested 5.0.0.beta.2 and as far as I can tell it fixes the issue. 

I've submitted two pull request for haml-rails and html2haml to make them allow 5.0.0:
- https://github.com/indirect/haml-rails/pull/128
- https://github.com/haml/html2haml/pull/80

**Comment by k0kubun** [comment] 2017-04-08 00:24
Ah, good point. Thanks!
