### ISSUE TITLE
Error when using .css.scss.erb under jruby9000

### ISSUE THREAD

**Issue by samu** [haml/haml#852] opened 2015-07-31 13:08 UTC
We have a brand new rails 4 app with an scss file that also needs to be processed by erb. 

We run it under `jruby9000`. Everything works fine, though when we add the haml gem to the gemfile, we suddenly get this error:

```
no implicit conversion of nil into String
  (in /code/myapp/app/assets/stylesheets/application.css.scss.erb)
```

At this point we don't even have any haml files.

This is only a problem with jruby9000, it works fine with jruby 1.7.21 and cruby.

**Comment by k0kubun** [comment] 2017-03-28 16:19
```
no implicit conversion of nil into String
  (in /code/myapp/app/assets/stylesheets/application.css.scss.erb)
```

This error log is insufficient. Please provide full backtrace. And since this is caused by jruby 1.7.21...jruby9000, isn't it JRuby's bug? So closing this for now.

In addition, JRuby is tested on Travis CI of Haml and it passes. Please try latest Haml: 5.0.0.beta.2. Feel free to reopen this if you still have the problem with it.

**Closed by k0kubun** 2017-03-28 16:19 UTC
