### ISSUE TITLE
SyntaxError: [stdin]:1:67: octal literal '05' must be prefixed with '0o'

### ISSUE THREAD

**Issue by pcboy** [haml/haml#927] opened 2017-05-11 09:04 UTC
I encounter a strange problem with Haml 5.0.1
When I'm using the `:coffeescript` tag in an haml file in my rails project, I get:
```
ActionView::Template::Error (SyntaxError: [stdin]:1:67: octal literal '05' must be prefixed with '0o'):
```
I do not have this problem with haml 4.0.7 that I was using before.
Am I missing something?

**Comment by k0kubun** [comment] 2017-05-12 07:16
There are too few information to help you.

Please provide at least:

- **Complete Haml template you're using or minimized fragment that can reproduce your problem**
- Gem versions of coffee-script, coffee-script-source

And following things are nice to have:

- Gem version of execjs
- Type of execjs's engine and its version
  - If you use therubyracer, the version of therubyracer
  - If you have nodejs on your environment, the version of nodejs

**Comment by k0kubun** [comment] 2017-05-12 07:27
## Reproductive steps
Given Haml template:

```haml
:coffeescript
  a = 05
```

- haml v5.0.1
- coffee-script v2.4.1
- coffee-script-source v1.12.2

## Solution
> Am I missing something?

I found the cause: https://github.com/atmos/camo/issues/11 https://github.com/jashkenas/coffeescript/commit/46ff7705
You should just need to read and follow the error message.

```diff
 :coffeescript
-  a = 05
+  a = 0o05
```

<hr>

It's definitely coffee-script side's issue. So closing this issue.

This error caused by your Haml upgrade may be just a coincidence. Did you confirm your Gemfile.lock diff on Haml upgrade?

**Closed by k0kubun** 2017-05-12 07:27 UTC
