### ISSUE TITLE
Hackathon

### ISSUE THREAD

**Issue by hcatlin** [haml/haml#979] opened 2018-02-18 21:41 UTC
@amatsuda @mattwildig @teeparham @k0kubun 

Hey Haml Team!

I'm coming back from the maintainer grave for a little bit because I'm helping out next weekend at [Hackillinois](https://www.hackillinois.org/) and we're supposed to help the students find an open source project to help out on.

Well, out of all the projects I've been involved in, Haml seems like a pretty good one to have them come in and tackle some issues and maybe work on some features.

I'm going through and trying to pick out some issues that I thought might be good for them, and marking them with Help Wanted.

If there are any projects, features, or issues you would love to see get tackled, just let me know.

I'm hopeful we can maybe even get a release out, based off their work!

-h.

**Comment by k0kubun** [comment] 2018-02-19 01:09
Here are my suggestions:

## Good for introduction
* Comment your thoughts on issues which are not listed in this comment. They need a discussion.
* Investigate how Haml documentation is generated and fix https://github.com/haml/haml/issues/928
* Document that we no longer have `--ugly` option and pretty mode is dropped in Haml 5 https://github.com/haml/haml/issues/938

## Normal difficulty, but interesting
* Honor `:/` flag in haml_tag for any format https://github.com/haml/haml/issues/939
* Fix parser to allow comments in anywhere https://github.com/haml/haml/issues/815
* Fix error with empty :javascript section https://github.com/haml/haml/issues/947 (duplicated with https://github.com/haml/haml/issues/970)
* Fix compilation error in empty block https://github.com/haml/haml/issues/954
* Remove `#inspect` dependencies in static compilation for some values, at least for `true`/`false` https://github.com/haml/haml/issues/972

## A little harder
* HTTP streaming for Rails https://github.com/haml/haml/issues/436
  * You need to know how Slim achieves HTTP streaming. Now this can be relatively easily implemented because we are already on Temple framework.
* Reproduce bug in combination with Erubi/Erubis on Rails and fix it https://github.com/haml/haml/issues/870
* Reproduce bug around XssMods and fix it https://github.com/haml/haml/issues/814
* Fix bug with multiple :erb tag on Rails https://github.com/haml/haml/issues/968

**Comment by hcatlin** [comment] 2018-02-19 19:59
@k0kubun ありがとうございました!

This is totally fantastic. Wow, you are going to make my job so easy!

**Comment by k0kubun** [comment] 2018-09-05 13:33
Hackillinois 2018 seems to have been held during Feb 23-25. Let's close this until we prepare for Hackillinois 2019.

**Closed by k0kubun** 2018-09-05 13:33 UTC
