### ISSUE TITLE
#capture_haml omits content

### ISSUE THREAD

**Issue by der-flo** [haml/haml#931] opened 2017-05-23 09:12 UTC
**Introduction:** I'm actually trying to develop a framework for UI components for one of our complex rails projects. It's somewhat similar to [Cells](http://trailblazer.to/gems/cells/), but allows you to specify multiple blocks of Haml code as parameters for such a component.

**Problem:** `Haml::Helpers#capture_haml` omits content in special situations.

**Example:** (reduced to the problem)

```ruby
require 'haml'

haml = <<HAML
=ui_component do |comp|
  component content

  - comp.my_block do
    my_block content
HAML

class HamlCaptureHelper
  include Haml::Helpers
  def initialize
    init_haml_helpers
  end

  def cap(&block)
    capture_haml(&block)
  end
end

class ComponentContext
  def initialize capture_helper
    @capture_helper = capture_helper
  end

  def my_block(&block)
    puts '... my_block captured:'
    puts @capture_helper.cap(&block)
    puts '......................'
    puts
  end
end

class HamlContext
  def initialize capture_helper
    @capture_helper = capture_helper
  end

  def ui_component
    ctx = ComponentContext.new(@capture_helper)
    content = @capture_helper.cap { yield ctx }

    puts '... ui_component captured:'
    puts content
    puts '..........................'

    # content
    nil
  end
end

capture_helper = HamlCaptureHelper.new
context = HamlContext.new(capture_helper)
haml_engine = Haml::Engine.new(haml)
haml_engine.render(context)
```

**Output:**

```
... my_block captured:
my_block content
......................

... ui_component captured:

..........................
```

In this example the string `component content` is omitted. `HamlContext#ui_component` doesn't record this part.

It somewhat relates to the fact that I'm using the same `haml_buffer` for all `#capture_haml` calls, but debugging this problem seems too hard for me.

Does anybody have good hints for me?

**Comment by k0kubun** [comment] 2017-05-24 02:08
This https://github.com/haml/haml/blob/v5.0.1/lib/haml/helpers.rb#L377 must be called in the same binding as the place Haml's compiled code is executed. Capturing depends on not only code to render a template but also binding which is created by original compiled code. You can never use `capture_haml` in separated class and pass only block to it. 

Every piece of code to render a template is not functional and depends on former results, so you shouldn't bring block by yourself unless you really understand what Haml does in compiled code. If you really want to know, see `Haml::Engine.new(haml).compiler.precompiled_with_ambles([])`, understand it by yourself and do it on your risk. Such usage is totally unexpected and its backward compatibility won't be ensured.

It is unexpected usage of `capture_haml` for Haml and not a bug, closing.

**Closed by k0kubun** 2017-05-24 02:08 UTC

**Comment by der-flo** [comment] 2017-05-29 08:05
Thanks for your assessment.
