### ISSUE TITLE
Unexpected errors on empty filters

### ISSUE THREAD

**Issue by f6p** [haml/haml#970] opened 2017-12-01 09:41 UTC
Hello,

after recent haml update (from 4.0.7 to 5.0.4) I noticed that filters may raise unexpected errors when there is no content. For example in 4.0 it was safe to have `:css` with no content. After update to 5.0 when `:css` have no content css filter will receive `nil` as text argument and will fail trying to do `text.rstrip`.

https://github.com/haml/haml/blob/c1b38ed87319a0c23e0247a3eb574cf88bce8bb5/lib/haml/filters.rb#L236

It looks like previously strings were passed to filters but now if there is no content filter will receive `nil` instead. So some filters will raise unexpected errors while others won't depending on how they are implemented.

**Comment by oniofchaos** [comment] 2018-10-11 05:04
It seems like maybe this could be solved with a deprecation warning/error? It shouldn't be surprising that major version upgrades come with breaking changes.

**Comment by k0kubun** [comment] 2020-06-21 01:26
Could you provide a minimum template which reproduces the problem? I haven't been able to reproduce your problem so far.

```
$ cat a.haml
:css
$ haml -v
Haml 5.1.2
$ haml a.haml
<style>

</style>
```

**Comment by k0kubun** [comment] 2020-06-21 01:28
Well, looks like I merged a patch which fixed the issue :sweat_smile: https://github.com/haml/haml/pull/986

**Comment by k0kubun** [comment] 2020-06-21 01:28
So please try the latest Haml.

**Closed by k0kubun** 2020-06-21 01:28 UTC
